### ISSUE TITLE
Messages Import Export issue

### ISSUE THREAD

**Issue by ghost** [FossifyOrg/Messages#88]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 8.1

### Affected device model

Moto G5 Plus

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open app, go to settings and click on export messages.
2. It asks for file name without .json
3. Android system may ask you to complete task with native android files or any other file manager installed on device (in my case fossify file manager).
4. Choose location for exporting. 
5. Now try to import same that just exported.

### Expected behavior

It should be imported without any issues and restore all the SMS and MMS.

### Actual behavior

While trying to import same file, it always prompt native android files and the exported file stays greyed out and not able to select it. It also doesn't contain any extensions by default (especially if exported via fossify file manager). But adding extension .json manually doesn't help much either. In my observations, if file is exported via native android files, added .json when android files asks for name and exporting it to "Downloads" directory only works. Even if I export it to any other location other than downloads, it still stays greyed out.

### Additional information

It could be fossify file manager bug as I tried to export back-up from Notally, extension was always missing. Also similar bug is reported as (https://github.com/FossifyOrg/Notes/issues/13). But it doesn't explain why this works in only Download folder and not to any other location.

**Comment by biopsin** [comment]
Duplicate of https://github.com/FossifyOrg/Messages/issues/6

**Comment by Aga-C** [comment]
@biopsin From the descriptions, these two are completely different. Here the file is exported, but without extension, so it can't be imported.

**Comment by biopsin** [comment]
But what sizes is the exported file?

**Comment by tom93** [comment]
There are two separate issues:

1. Missing .json extension on export. As you wrote, very similar to [FossifyOrg/Notes#13](https://github.com/FossifyOrg/Notes/issues/13). I'll open a PR.

2. Android reports the MIME type as "application/octet-stream" for .json files outside the Download folder. I can reproduce this on Android 9. In particular, if I export to the Download folder (even without the .json extension) then the MIME type is reported as "application/json" (using "Get info" in the native Files app), and if I move this file outside the Download folder (e.g. into Pictures) then the MIME type is reported as "application/octet-stream". I'm not sure why that is (I suspect the Download folder stores additional metadata, but I can't find any reference).
   As a workaround, how about adding "application/octet-stream" to the list of allowed file types?

**Comment by tom93** [comment]
@Abcd1234-dot Do you want to check check if #136 and #137 fix this issue for you? They do for me.

(I'm not a project member so you shouldn't trust me, but if you don't want to build from source / wait for a project member to build, then I've attached an APK file that I built myself: [unofficial-messages-2-foss-debug-for-issue-88.apk.zip](https://github.com/FossifyOrg/Messages/files/14623726/unofficial-messages-2-foss-debug-for-issue-88.apk.zip).)

**Comment by tom93** [comment]
> the apk file you attached is compiled one from the source code of fossify messages and includes your fix?

Yes. (I had to put it in a .zip file because GitHub limits attachment file types.)

@naveensingh Are you okay with me building and uploading APKs like that for testing?

**Comment by naveensingh** [comment]
@tom93 Yeah, it's okay. As these things can be risky in general, there will be some guidelines later. I'll be setting up workflows to build APKs automatically so PR authors don't have to do it themselves but it'll require a PR to have `testers needed` label (see https://github.com/FossifyOrg/Launcher/pull/12).

**Comment by tom93** [comment]
I'm glad it fixed the file selection issue. I don't know why the import isn't working, I tried reproducing in an Android 8 emulator but it worked fine for me.

I'm not sure how to debug the new issue. All I can think of is to open the .json file in a text editor (might need to rename to .txt) and check that it actually contains the messages you expect. And the adb logs might be useful if you are able to get them.

I hope the devs can help more...

--- 

For reference, here are my steps:

1. Receive a fake SMS (emulator controls: "..." > Phone > Send Message)
2. Open Fossify Messages and reply (it will be stuck in "Sending...", that's fine)
3. Export messages
4. Delete the conversation
5. Import messages

The messages reappear correctly. The only difference compared to what you described is that the "Import messages" popup disappears as soon as I click "OK". I also tested with MMS.

---

> I think this issue exists in all apps which allows import export backups

Do you mean the missing .json extension and file selection issue? If so, I've mentioned porting those fixes (https://github.com/FossifyOrg/Messages/pull/136#issuecomment-2001994711, https://github.com/FossifyOrg/Messages/pull/137#issue-2189992661) and I plan to follow up on that once approved.

**Comment by tom93** [comment]
Getting the Android logs is a bit of a hassle*.

But since you're okay with running debug builds, and since the import code is fairly short, I can add some custom debugging code that will log what it's doing to a text file in the Download folder. That might be enough to identify the issue.

\*To get the Android logs, you need to [download the platform tools](https://developer.android.com/tools/releases/platform-tools), [enabled developer mode and USB debugging](https://developer.android.com/studio/debug/dev-options) on your phone, and then run [adb](https://developer.android.com/tools/adb) [logcat](https://developer.android.com/tools/logcat) from the command line.

P.S. For future reference, if you're having trouble opening large text files on a PC, I recommend trying Notepad, WordPad (included with Windows until Windows 11), or installing [Notepad++](https://notepad-plus-plus.org/). But since the issue also happens with the new small backup, we should focus on that.

**Comment by tom93** [comment]
Great. You can view my email by appending ".patch" to any of my commits ([example](https://github.com/FossifyOrg/Messages/pull/137/commits/79c9909e76e021b18da338aefd11c0355760450f.patch), from #137).

If you want to limit the logs, you can try to identify the relevant parts by searching for words such as "fossify", "fatal", "exception", and "error". Stack traces from crashes are typically the jackpot, they look like this:

```
--------- beginning of crash
12-17 11:23:20.841 30867 31904 E AndroidRuntime: FATAL EXCEPTION: Thread-18
12-17 11:23:20.841 30867 31904 E AndroidRuntime: Process: org.fossify.messages, PID: 30867
12-17 11:23:20.841 30867 31904 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate ... [or some other error/exception]
12-17 11:23:20.841 30867 31904 E AndroidRuntime: 	at java.util.Arrays.copyOf(Arrays.java:3257)
12-17 11:23:20.841 30867 31904 E AndroidRuntime: 	at kb.m.a(SourceFile:12)
12-17 11:23:20.841 30867 31904 E AndroidRuntime: 	at kb.f.i(SourceFile:19)
12-17 11:23:20.841 30867 31904 E AndroidRuntime: 	at kb.v.t(SourceFile:8)
12-17 11:23:20.841 30867 31904 E AndroidRuntime: 	...
12-17 11:23:20.841 30867 31904 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
12-17 11:23:20.842 1507 7831 W ActivityTaskManager: Force finishing activity org.fossify.messages/.activities.SettingsActivity
```

The short names in lines such as "at kb.m.a(SourceFile:12)" are not sensitive, they refer to locations in the source code and can be converted to the full names (see https://github.com/FossifyOrg/Messages/issues/6#issuecomment-2000602127).

I just noticed that you *only* get the "Importing..." message. There should also be an "Importing successful" message after that. I'm pretty certain that you are not seeing the second message (and that the dialog is not closing) due to an uncaught exception (as in the above example), which is very promising.

**Comment by tom93** [comment]
Hmm. I had a look at the log that you sent, there were no relevant crashes, but based on the debug messages of the form "D/MmsSmsProvider( 2504): getSingleAddressId: insert new canonical_address for xxxxxx, _id=58" it looks like it *is* importing, just doing it really slowly (the timestamps show it was importing for ~4 minutes and then it seem like you killed the app).

I suspect the calls to `contentResolver.insert()` are slow, which should be fairly easy to fix (use batching and [bulkInsert](https://developer.android.com/reference/android/content/ContentResolver#bulkInsert(android.net.Uri,%20android.content.ContentValues[])).

If you're up for an experiment, I'm curious what would happen if you try importing the smaller backup again and just leave it running for a couple of hours (e.g. overnight when you're not using your phone). I predict that the import will succeed eventually.

Alternatively, just wait until I write a PR.

**Comment by tom93** [comment]
The importer is supposed to detect whether the messages already exists, and skip importing ones that already exist.

Please don't do anything risky though (the ideal situation would be to import on a test device; I don't advise deleting the messages on your main device, even though in theory it should be possible to restore from the backup).

The import won't necessarily take the same amount of time as the export, because the code is different and might be slower. One idea is to try only importing SMS or only importing MMS (it's unclear which would be faster -- MMS are large but I assume there are fewer of them).

I've thought some more about making the import faster. It should be fairly easy to implement bulk insert & query, so feel free to just wait a couple of days until I put that together. (Implementing proper error handling that tries to import all the messages even if some of them cause errors is trickier, but that part isn't required for testing.)

Re opening the .json file, I'm not sure which program you are using to open it, but you can definitely open it with Notepad/WordPad (even though the extension is .json rather than .txt), you just need to use right click > "Open with", or temporarily rename the file. It just won't look pretty (and it might be too large for Notepad; but WordPad should be able to handle it).

**Comment by tom93** [comment]
> Your fix works.

Great!

> > I guess the best approach is to provide better progress indication ([example](https://developer.android.com/develop/ui/views/notifications/build-notification#progressbar)).
> 
> there was no progress indication in notification tho.

Yeah, the notification was just an idea. The APK I build only has the debug messages (which should appear on-screen as [toasts](https://developer.android.com/guide/topics/ui/notifiers/toasts) like the original "Importing..." message).

> all the imported messages are showing up randomly in the app! and not sorted by date i.e. latest ones on top and oldest ones on bottom.

Yeah, I noticed that when I was testing. I'll split that off into a new issue.

**Comment by tom93** [comment]
> So we can successfully close this issue when your PR gets merged?

Yes, it's better to create separate issues to track the new bugs, and allow this issue to be closed automatically when #137 is merged (that's the fix for the greyed-out files issue you originally reported).

> I hope you will start working on that as soon as possible as i already messed up with existing sms :') I have backed up before testing and i hope to restore them properly soon.

Well, I'm not a project member (as I said before), so don't pin your hopes on me. I did spot something that might help and I was going to test that, but if it doesn't work out I'll probably leave it to the devs.

**Comment by tom93** [comment]
I found a workaround for the timestamp issue (which turns out to be an Android bug) and built a new APK with all the relevant patches, including a patch for a [serious issue](https://github.com/FossifyOrg/Messages/issues/148) I discovered along the way. The code is in branch "all-import-fixes" of my fork ([commits](https://github.com/FossifyOrg/Messages/compare/master...d480fdc019f5528edc75910b4091be2f0e5bd612)). Here is the APK: [unofficial-messages-all-import-fixes.apk.zip](https://github.com/FossifyOrg/Messages/files/14735262/unofficial-messages-all-import-fixes.apk.zip)

It should display the same debugging messages as before, but with a new debug message of the form "Fixing dates for *N* conversations" at the very end.

**Comment by tom93** [comment]
Great.

> I think time stamp issue still exist for MMS but I am not 100% sure so someone needs to cross verify it.

You're right. My last APK included temporary patch that updates the conversation timestamps even if the message already exists, but I only did that for SMS (not for MMS). If you are importing a new MMS though, then the conversation timestamp should be updated.

> Another thing thing I want to mention is, app takes time to reflect new changes especially if large number of changes i.e. large backup is restored.

> whenever i launch official Fossify messages app, it takes around 5 seconds to get open and showing threads which was not happening before

You should probably create a new issue for that. I tried to reproduce this; the first time I open the app it takes several seconds to load the new messages, but the next time I open the app it's near-instant (with 3000 messages across 1000 conversations, based on my example backup from #143). If the app is slow for you *each time you open it* then that's unacceptable, but if it's only slow during the first launch then it might be inevitable (would still be nice if it could be faster or showed progress, so still worth filing an issue).

> If I export using the last apk you provided, it is not appending .json to export file

Yes, I didn't bother including the .json suffix patch in my last APK, sorry for the confusion.

**Comment by tom93** [comment]
> the time stamp was not fixed for MMS

I tested this and I can reproduce this issue. It's due to a bug in Android -- the code [here](https://android.googlesource.com/platform/packages/providers/TelephonyProvider/+/android14-release/src/com/android/providers/telephony/MmsSmsDatabaseHelper.java#464) only updates the date and snippet for threads that contain at least one SMS, so it skips over threads that only contain MMS. Ideally this should be [reported to Google](https://source.android.com/docs/setup/contribute/report-bugs) but I'm not planning to do this myself.

There is not much that can be done from the app's side. The app could ignore the date & snippet reported by Android and instead recompute them on the app's side, but that seems like too much work to me.

**Comment by BlastboomStrice** [comment]
> I found a workaround for the timestamp issue (which turns out to be an Android bug) and built a new APK with all the relevant patches, including a patch for a [serious deletion issue](https://github.com/FossifyOrg/Messages/issues/148) I discovered along the way. The code is in branch "all-import-fixes" of my fork ([all commits](https://github.com/FossifyOrg/Messages #/compare/master...d480fdc019f5528edc75910b4091be2f0e5bd612), [actual workaround](https://github.com/FossifyOrg/Messages/commit/e006a910960f630b19532e78a35bb8a8b49b8e99)). Here is the APK: [unofficial-messages-all-import-fixes.apk.zip](https://github.com/FossifyOrg/Messages/files/14735262/unofficial-messages-all-import-fixes.apk.zip)

I can confirm that this worked for me too!
Device: Xiaomi Mi 10 (umi)
Android 14
OS: HyperOS
Thank you very much!!

**Comment by ways** [comment]
I was unable to import my backup until I found this issue. Moving the file to Downloads and renaming to .json fixed it. Thanks!
